site_name: QuisitivePnP
theme:
  name: readthedocs
nav:
    - Home: index.md
    - CatPowerShell:
        - Overview: CatPowerShell\Documentation.md
        - Organization: CatPowerShell\Organization.md
        - Contribution: CatPowerShell\Contribution.md
        - 'Client Use': CatPowerShell\ClientUse.md
        - Naming: CatPowerShell\Naming.md
        - 'Creating New Script': CatPowerShell\NewScripts.md
        - 'Request Access': 'https://forms.office.com/r/QxWWn2RQVA'