site_name: CatPnP
theme:
  name: bootstrap4
nav:
    - Home: index.md
    - CatPowerShell:
        - 'Request Access': 'https://forms.office.com/Pages/ResponsePage.aspx?id=4p1l0E5ovUmbHx_UzQlC2R_QqG2HNm9CqBYcit9jIBlUQ1RGUFVMNlEwNlA2NUYzTDVWSlRMT0JHSy4u'
        - Documentation: CatPowerShell\Documentation.md